#!/bin/bash

docker run -d \
--volume=`pwd`/data/mysql:/var/lib/mysql \
--restart=always \
--publish=3306:3306 \
--env='MYSQL_USER=wp-user' \
--env='MYSQL_PASSWORD=myAwesomePassword' \
--env='MYSQL_DATABASE=wordpress' \
--env='MYSQL_ROOT_PASSWORD=myAwesomeRootPassword' \
--name=mysql \
mysql:5.7
